language: go
go:
  - '1.12.x'
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
script:
  - dep ensure -v
  - go test -v
cache:
  directories:
    - $GOPATH/pkg/dep # cache dep downloaded dependencies
before_deploy:
  - ./build.sh
deploy:
  provider: releases
  api_key: "$OAUTHTOKEN"
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true